###
POST https://gmail.googleapis.com/gmail/v1/users/me/watch
# headers: {
#       Authorization: `Bearer ${accessToken}`,
#       "Content-type": "application/json",
#     },

###
POST http://14.225.192.183:8200/api/watch
###